from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Dict, Iterable, List, Optional

from python.publishing.ids.id_policy import build_pattern_id
from python.publishing.pattern_library.pattern_enricher import enrich_pattern_record
from python.publishing.pattern_library.pattern_generator_formulas import (
    available_formula_families,
    build_formula_pattern,
)
from python.publishing.pattern_library.pattern_generator_paths import (
    available_path_families,
    build_path_pattern,
)
from python.publishing.pattern_library.pattern_identity import build_variant_code
from python.publishing.pattern_library.pattern_registry import PatternRegistry
from python.publishing.pattern_library.pattern_validator import validate_pattern_record_strict
from python.publishing.schemas.models import PatternRecord


GENERATOR_VERSION = "pattern_generator_v1"


@dataclass
class GeneratedPatternResult:
    added_patterns: List[PatternRecord]
    skipped_duplicates: List[str]
    validation_failures: List[Dict[str, object]]


def _now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def available_generator_families() -> List[str]:
    return sorted(set(available_formula_families()) | set(available_path_families()))


def _build_family_payload(family_id: str, variant: int) -> dict:
    key = str(family_id).strip().lower()
    if key in set(available_formula_families()):
        return build_formula_pattern(key, variant)
    if key in set(available_path_families()):
        return build_path_pattern(key, variant)
    raise KeyError(f"Unsupported generator family: {family_id}")


def generate_patterns_into_registry(
    *,
    registry: PatternRegistry,
    library_short: str,
    family_ids: Iterable[str],
    count: int,
    created_at: Optional[str] = None,
    updated_at: Optional[str] = None,
    author: str = "system",
) -> GeneratedPatternResult:
    if count <= 0:
        raise ValueError("count must be >= 1")

    families = [str(f).strip().lower() for f in family_ids if str(f).strip()]
    if not families:
        raise ValueError("At least one family must be supplied")

    timestamp_created = created_at or _now_iso()
    timestamp_updated = updated_at or timestamp_created

    added_patterns: List[PatternRecord] = []
    skipped_duplicates: List[str] = []
    validation_failures: List[Dict[str, object]] = []

    next_ordinal = registry.get_next_ordinal()

    for i in range(count):
        family_id = families[i % len(families)]
        variant = i // len(families)

        payload = _build_family_payload(family_id, variant)
        mask81 = str(payload["mask81"])
        clue_count = sum(1 for ch in mask81 if ch == "1")

        pattern = PatternRecord(
            pattern_id=build_pattern_id(library_short, next_ordinal),
            library_id=registry.library_id,
            name=str(payload["name"]),
            slug="",
            aliases=[],
            description=str(payload["description"]),
            grid_size=9,
            layout_type="classic9x9",
            mask81=mask81,
            canonical_mask_signature="",
            clue_count=clue_count,
            symmetry_type="none",
            visual_family=str(payload.get("family_id") or "generated"),
            family_id=str(payload["family_id"]),
            family_name=str(payload["family_name"]),
            variant_code=build_variant_code(family_name=payload["family_name"], ordinal=variant + 1),
            tags=list(payload.get("tags", [])),
            status="active",
            source_type="generated",
            source_ref=str(payload.get("source_ref") or GENERATOR_VERSION),
            author=author,
            notes=f"Generated by {GENERATOR_VERSION}",
            is_verified=False,
            created_at=timestamp_created,
            updated_at=timestamp_updated,
        )

        pattern = enrich_pattern_record(pattern)
        errors = validate_pattern_record_strict(pattern)
        if errors:
            validation_failures.append(
                {
                    "name": pattern.name,
                    "family_id": family_id,
                    "errors": errors,
                }
            )
            continue

        was_added = registry.add_or_skip_duplicate_mask(pattern)
        if not was_added:
            skipped_duplicates.append(pattern.name)
            continue

        added_patterns.append(pattern)
        next_ordinal += 1

    return GeneratedPatternResult(
        added_patterns=added_patterns,
        skipped_duplicates=skipped_duplicates,
        validation_failures=validation_failures,
    )