name: Android

on:
  push:
  pull_request:

jobs:
  assembleDebug:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python/mobile/android

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK components (platform/build-tools/CMake/NDK)
        shell: bash
        run: |
          set -e
          SDKMANAGER="${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager"
          yes | "$SDKMANAGER" --licenses || true
          "$SDKMANAGER" \
            "platform-tools" \
            "platforms;android-34" \
            "build-tools;34.0.0" \
            "cmake;3.22.1" \
            "ndk;26.1.10909125"

      - name: Export NDK/CMake to env
        shell: bash
        run: |
          set -e
          echo "ANDROID_NDK_HOME=${ANDROID_SDK_ROOT}/ndk/26.1.10909125" >> $GITHUB_ENV
          echo "${ANDROID_SDK_ROOT}/cmake/3.22.1/bin" >> $GITHUB_PATH
          cmake --version

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Fix Gradle wrapper line endings
        shell: bash
        run: |
          set -e
          sed -i 's/\r$//' gradlew
          chmod +x gradlew

      # Fetch OpenCV Android SDK into the location expected by :openCV sourceSets
      - name: Fetch OpenCV Android SDK 4.9.0
        shell: bash
        run: |
          set -e
          OPENCV_ZIP="opencv-4.9.0-android-sdk.zip"
          OPENCV_URL="https://github.com/opencv/opencv/releases/download/4.9.0/${OPENCV_ZIP}"
          mkdir -p app/src/main/cpp/third_party
          cd app/src/main/cpp/third_party
          if [ ! -d "OpenCV-android-sdk" ]; then
            curl -L "$OPENCV_URL" -o "$OPENCV_ZIP"
            unzip -q "$OPENCV_ZIP"
            mv OpenCV-android-sdk OpenCV-android-sdk
            rm -f "$OPENCV_ZIP"
          fi

      - name: Kotlin compile (show errors clearly)
        shell: bash
        run: ./gradlew clean :app:compileDebugKotlin --stacktrace --info --warning-mode all

      - name: Assemble Debug
        shell: bash
        run: ./gradlew :app:assembleDebug --stacktrace --no-daemon

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk