name: Android

on:
  push:
  pull_request:

jobs:
  assembleDebug:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python/mobile/android

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 🔧 Install Android SDK + cmdline-tools (gives us `sdkmanager`)
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # Accept licenses & install exact components we need
      - name: Install Android SDK components (platform/build-tools/CMake/NDK)
        shell: bash
        run: |
          set -e
          SDKMANAGER="${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager"
          yes | "$SDKMANAGER" --licenses || true
          "$SDKMANAGER" "platform-tools" \
                        "platforms;android-34" \
                        "build-tools;34.0.0" \
                        "cmake;3.22.1" \
                        "ndk;26.1.10909125"

      - name: Export NDK/CMake to env
        shell: bash
        run: |
          set -e
          echo "ANDROID_NDK_HOME=${ANDROID_SDK_ROOT}/ndk/26.1.10909125" >> $GITHUB_ENV
          echo "${ANDROID_SDK_ROOT}/cmake/3.22.1/bin" >> $GITHUB_PATH
          cmake --version

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      # 🧹 Fix CRLF + exec bit so Linux can run gradlew
      - name: Fix Gradle wrapper line endings
        shell: bash
        run: |
          set -e
          sed -i 's/\r$//' gradlew
          chmod +x gradlew

      # 📦 Fetch OpenCV Android SDK into the path your CMakeLists expects
      - name: Fetch OpenCV Android SDK
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p app/src/main/cpp/third_party
          cd app/src/main/cpp/third_party

          echo "Downloading OpenCV Android SDK…"
          curl -L -o opencv.zip https://github.com/opencv/opencv/releases/download/4.10.0/opencv-4.10.0-android-sdk.zip

          echo "Unzipping…"
          unzip -q opencv.zip

          # Find the extracted folder (case-insensitive match on *android-sdk)
          SRC_DIR="$(find . -maxdepth 1 -type d -iname '*android-sdk' -printf '%f\n' | head -n1 || true)"
          if [[ -z "${SRC_DIR:-}" ]]; then
            echo "ERROR: Could not locate extracted OpenCV SDK directory"
            ls -la
            exit 1
          fi

          # Normalize to the path CMake expects
          if [[ "${SRC_DIR}" != "OpenCV-android-sdk" ]]; then
            mv "$SRC_DIR" OpenCV-android-sdk
          fi

          test -d OpenCV-android-sdk/sdk/native/jni/include/opencv2
          echo "OpenCV SDK ready at: $(pwd)/OpenCV-android-sdk"

      - name: Assemble Debug
        shell: bash
        run: ./gradlew :app:assembleDebug --stacktrace --no-daemon

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk